Repository goormthon-Univ/2024_BEOTKKOTTHON_TEAM_29_BE, pull requests merged in 2024-03, with the labels that each got.

#3 feature/create entity
  src/main/java/com/goormthon/tomado/domain/category/entity/Category.java
  src/main/java/com/goormthon/tomado/domain/category/entity/ColorType.java
  src/main/java/com/goormthon/tomado/domain/club/entity/Club.java
  src/main/java/com/goormthon/tomado/domain/club/entity/ClubMembers.java
  src/main/java/com/goormthon/tomado/domain/club/entity/ClubMembersId.java
  src/main/java/com/goormthon/tomado/domain/memo/entity/Memo.java
  src/main/java/com/goormthon/tomado/domain/task/entity/Task.java
  src/main/java/com/goormthon/tomado/domain/tomado/entity/Tomado.java
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
  src/main/java/com/goormthon/tomado/domain/user/entity/UserTomado.java
  src/main/java/com/goormthon/tomado/domain/user/entity/UserTomadoId.java
Labels: enhancement

#4 feature/settings common
  src/main/java/com/goormthon/tomado/common/ApiResponse.java
  src/main/java/com/goormthon/tomado/common/exception/BadRequestException.java
  src/main/java/com/goormthon/tomado/common/exception/BaseException.java
  src/main/java/com/goormthon/tomado/common/exception/ConflictException.java
  src/main/java/com/goormthon/tomado/common/exception/ControllerExceptionAdvice.java
  src/main/java/com/goormthon/tomado/common/exception/ForbiddenException.java
  src/main/java/com/goormthon/tomado/common/exception/NotFoundException.java
  src/main/java/com/goormthon/tomado/common/exception/UnauthorizedException.java
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/ExceptionHandlerFilter.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
Labels: enhancement

#6 feature/user
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/domain/user/controller/UserController.java
  src/main/java/com/goormthon/tomado/domain/user/dto/LoginIdCheckDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserChangeDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserInfoDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserLoginDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserSignUpDto.java
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
  src/main/java/com/goormthon/tomado/domain/user/repository/UserRepository.java
  src/main/java/com/goormthon/tomado/domain/user/service/UserService.java
Labels: enhancement

#9 feat: user
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/config/PasswordEncoderConfiguration.java
  src/main/java/com/goormthon/tomado/domain/user/controller/UserController.java
  src/main/java/com/goormthon/tomado/domain/user/dto/LoginIdCheckDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserChangeDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserInfoDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserLoginDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserResponseDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserSignUpDto.java
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
  src/main/java/com/goormthon/tomado/domain/user/repository/UserRepository.java
  src/main/java/com/goormthon/tomado/domain/user/service/UserService.java
Labels: enhancement

#13 feature/swagger
  build.gradle
  src/main/java/com/goormthon/tomado/config/SwaggerConfiguration.java
  src/main/java/com/goormthon/tomado/domain/user/controller/TestController.java
  src/main/resources/application.yml
Labels: documentation

#17 16 feature/refactor user
  src/main/java/com/goormthon/tomado/domain/user/controller/UserController.java
  src/main/java/com/goormthon/tomado/domain/user/dto/ChangeRequest.java
  src/main/java/com/goormthon/tomado/domain/user/dto/LoginRequest.java
  src/main/java/com/goormthon/tomado/domain/user/dto/Response.java
  src/main/java/com/goormthon/tomado/domain/user/dto/SignUpRequest.java
  src/main/java/com/goormthon/tomado/domain/user/dto/SimpleResponse.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserChangeDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserInfoDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserLoginDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/UserSignUpDto.java
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
  src/main/java/com/goormthon/tomado/domain/user/service/UserService.java
Labels: refactoring

#15 feature/memo
  src/main/java/com/goormthon/tomado/TomadoApplication.java
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/domain/memo/controller/MemoController.java
  src/main/java/com/goormthon/tomado/domain/memo/dto/MemoDto.java
  src/main/java/com/goormthon/tomado/domain/memo/entity/Memo.java
  src/main/java/com/goormthon/tomado/domain/memo/repository/MemoRepository.java
  src/main/java/com/goormthon/tomado/domain/memo/service/MemoService.java
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
Labels: enhancement

#21 hotfix/swagger
  src/main/resources/application.yml
Labels: bug

#22 feature/task
  src/main/java/com/goormthon/tomado/TomadoApplication.java
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/domain/category/entity/Category.java
  src/main/java/com/goormthon/tomado/domain/task/controller/TaskController.java
  src/main/java/com/goormthon/tomado/domain/task/dto/SaveTomaRequest.java
  src/main/java/com/goormthon/tomado/domain/task/dto/TaskCreateDto.java
  src/main/java/com/goormthon/tomado/domain/task/dto/TomaCount.java
  src/main/java/com/goormthon/tomado/domain/task/dto/TomaCountListResponse.java
  src/main/java/com/goormthon/tomado/domain/task/entity/Task.java
  src/main/java/com/goormthon/tomado/domain/task/repository/TaskRepository.java
  src/main/java/com/goormthon/tomado/domain/task/service/TaskService.java
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
  src/main/resources/application.yml
Labels: enhancement

#24 feature/refactor category
  src/main/java/com/goormthon/tomado/domain/category/controller/CategoryController.java
  src/main/java/com/goormthon/tomado/domain/category/dto/CategoryListByDateDto.java
  src/main/java/com/goormthon/tomado/domain/category/dto/CategoryListDto.java
  src/main/java/com/goormthon/tomado/domain/category/service/CategoryService.java
Labels: refactoring

#25 feature/shop
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/domain/tomado/controller/TomadoController.java
  src/main/java/com/goormthon/tomado/domain/tomado/dto/TomadoDto.java
  src/main/java/com/goormthon/tomado/domain/tomado/repository/TomadoRepository.java
  src/main/java/com/goormthon/tomado/domain/tomado/service/TomadoService.java
  src/main/java/com/goormthon/tomado/domain/user/entity/UserTomado.java
  src/main/java/com/goormthon/tomado/domain/user/repository/UserTomadoRepository.java
Labels: enhancement

#29 refactor: 상점 조회 반환 값 변경
  src/main/java/com/goormthon/tomado/domain/tomado/controller/TomadoController.java
  src/main/java/com/goormthon/tomado/domain/tomado/dto/TomadoDto.java
  src/main/java/com/goormthon/tomado/domain/tomado/service/TomadoService.java
Labels: refactoring

#32 feature/book
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/domain/user/controller/UserController.java
  src/main/java/com/goormthon/tomado/domain/user/dto/BookResponse.java
  src/main/java/com/goormthon/tomado/domain/user/repository/UserTomadoRepository.java
  src/main/java/com/goormthon/tomado/domain/user/service/UserService.java
Labels: enhancement

#31 feature/category modify
  src/main/java/com/goormthon/tomado/domain/category/controller/CategoryController.java
  src/main/java/com/goormthon/tomado/domain/category/entity/Category.java
  src/main/java/com/goormthon/tomado/domain/category/service/CategoryService.java
  src/main/java/com/goormthon/tomado/domain/club/entity/ClubMembers.java
Labels: enhancement

#35 fix: give original tomado
  src/main/java/com/goormthon/tomado/domain/user/service/UserService.java
Labels: bug

#33 27 feature/club
  src/main/java/com/goormthon/tomado/common/response/ErrorMessage.java
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/domain/category/entity/Category.java
  src/main/java/com/goormthon/tomado/domain/category/service/CategoryService.java
  src/main/java/com/goormthon/tomado/domain/club/controller/ClubController.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubCreateDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubGetDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubUpdateDto.java
  src/main/java/com/goormthon/tomado/domain/club/entity/Club.java
  src/main/java/com/goormthon/tomado/domain/club/entity/ClubMembers.java
  src/main/java/com/goormthon/tomado/domain/club/repository/ClubMembersRepository.java
  src/main/java/com/goormthon/tomado/domain/club/repository/ClubRepository.java
  src/main/java/com/goormthon/tomado/domain/club/service/ClubService.java
  src/main/java/com/goormthon/tomado/domain/task/dto/TaskCreateDto.java
  src/main/java/com/goormthon/tomado/domain/task/service/TaskService.java
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
Labels: enhancement

#37 fix: user change
  src/main/java/com/goormthon/tomado/domain/user/entity/User.java
  src/main/java/com/goormthon/tomado/domain/user/service/UserService.java
Labels: bug

#39 38 feature/club invite
  src/main/java/com/goormthon/tomado/common/response/SuccessMessage.java
  src/main/java/com/goormthon/tomado/domain/club/controller/ClubController.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubGetDto.java
  src/main/java/com/goormthon/tomado/domain/club/entity/Club.java
  src/main/java/com/goormthon/tomado/domain/club/service/ClubService.java
Labels: new feature

#41 40 feature/task hard mode
  src/main/java/com/goormthon/tomado/domain/task/controller/TaskController.java
  src/main/java/com/goormthon/tomado/domain/task/dto/SaveTomaRequest.java
  src/main/java/com/goormthon/tomado/domain/task/service/TaskService.java
Labels: new feature

#43 refactor/task id return
  src/main/java/com/goormthon/tomado/domain/task/controller/TaskController.java
  src/main/java/com/goormthon/tomado/domain/task/dto/SaveTomaRequest.java
  src/main/java/com/goormthon/tomado/domain/task/service/TaskService.java
Labels: bug fix, refactoring

#46 refactor/club entity
  src/main/java/com/goormthon/tomado/domain/category/entity/ColorType.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubCreateDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubGetDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubUpdateDto.java
  src/main/java/com/goormthon/tomado/domain/club/entity/Club.java
  src/main/java/com/goormthon/tomado/domain/club/service/ClubService.java
Labels: refactoring

#50 feature: 구매/미구매 토마두 불러오기
  src/main/java/com/goormthon/tomado/domain/tomado/dto/TomadoDto.java
  src/main/java/com/goormthon/tomado/domain/tomado/service/TomadoService.java
Labels: new feature

#53 52 refactor/category
  src/main/java/com/goormthon/tomado/domain/category/dto/CategoryCreateDto.java
  src/main/java/com/goormthon/tomado/domain/category/dto/CategoryListByDateDto.java
  src/main/java/com/goormthon/tomado/domain/category/dto/CategoryUpdateDto.java
  src/main/java/com/goormthon/tomado/domain/category/entity/Category.java
  src/main/java/com/goormthon/tomado/domain/category/service/CategoryService.java
Labels: refactoring

#55 refactor/user
  src/main/java/com/goormthon/tomado/domain/user/controller/UserController.java
  src/main/java/com/goormthon/tomado/domain/user/dto/BookResponse.java
  src/main/java/com/goormthon/tomado/domain/user/dto/ChangeRequest.java
  src/main/java/com/goormthon/tomado/domain/user/dto/LoginDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/LoginIdCheckDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/LoginRequest.java
  src/main/java/com/goormthon/tomado/domain/user/dto/Response.java
  src/main/java/com/goormthon/tomado/domain/user/dto/SignUpDto.java
  src/main/java/com/goormthon/tomado/domain/user/dto/SignUpRequest.java
  src/main/java/com/goormthon/tomado/domain/user/dto/SimpleResponse.java
  src/main/java/com/goormthon/tomado/domain/user/repository/UserRepository.java
  src/main/java/com/goormthon/tomado/domain/user/service/UserService.java
Labels: refactoring

#57 refactor/shop
  src/main/java/com/goormthon/tomado/domain/tomado/controller/TomadoController.java
  src/main/java/com/goormthon/tomado/domain/tomado/service/TomadoService.java
Labels: refactoring

#59 54 refactor/task
  src/main/java/com/goormthon/tomado/domain/task/dto/SaveTomaRequest.java
  src/main/java/com/goormthon/tomado/domain/task/dto/TaskCreateDto.java
  src/main/java/com/goormthon/tomado/domain/task/service/TaskService.java
Labels: refactoring

#60 refactor/memo
  src/main/java/com/goormthon/tomado/domain/memo/controller/MemoController.java
  src/main/java/com/goormthon/tomado/domain/memo/dto/MemoDto.java
  src/main/java/com/goormthon/tomado/domain/memo/service/MemoService.java
Labels: refactoring

#62 refactor/club
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubCreateDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubGetDto.java
  src/main/java/com/goormthon/tomado/domain/club/dto/ClubUpdateDto.java
  src/main/java/com/goormthon/tomado/domain/club/repository/ClubMembersRepository.java
  src/main/java/com/goormthon/tomado/domain/club/service/ClubService.java
Labels: refactoring
